// state.home
export const RECEIVE_WORD_INPUT = 'RECEIVE_WORD_INPUT';
export const SUBMIT_WORD = 'SUBMIT_WORD';
export const FETCH_DEFINITION= 'FETCH_DEFINITION';
export const RECEIVE_DEFINITION = 'RECEIVE_DEFINITION';
export const RECEIVE_DEFINITION_ERROR = 'RECEIVE_DEFINITION_ERROR';
export const RESET_WORD_BOX= 'RESET_WORD_BOX';
export const ACTION_ALERT= 'ACTION_ALERT';
export const TAP_MENU_ICON= 'TAP_MENU_ICON';
export const CLOSE_MENU= 'CLOSE_MENU';
