// state.home
export const RECEIVE_WORD_INPUT = 'RECEIVE_WORD_INPUT';
export const SUBMIT_WORD = 'SUBMIT_WORD';
export const FETCH_DEFINITION= 'FETCH_DEFINITION';
export const RECEIVE_DEFINITION = 'RECEIVE_DEFINITION';
export const RECEIVE_DEFINITION_ERROR = 'RECEIVE_DEFINITION_ERROR';
